config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#home'

  resources :users, only: [:new, :show, :create] do
    resources :problems, only: [:index, :show, :new, :create, :destroy] do 
      member do 
        get :form_decision, :result_decision, :form_crossover
      end
      resources :decisions, only: [:index, :show, :new, :create] 
      resources :break_evens, only: [:index, :new, :show, :create, :destroy]
      resources :crossovers, only: [:index, :new, :show, :create]
    end
  end
  
  resources :decisions, only: [:destroy]
  resources :crossovers, only: [:destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


end

app/models/problem.rb
class Problem < ApplicationRecord
	belongs_to :user
	has_many :decisions
	has_many :break_evens
	has_many :crossovers
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
	def index
		problems = Problem.all
		render json: problems
	end

	def show
		@user = User.find_by(id: params[:user_id])
		@problem = @user.problems.find_by(id: params[:id])
	end

	def new
		@user = User.find_by(id: params[:user_id])
		@new_problem = Problem.new
	end

	def create
	    user = User.find_by(id: session[:user_id])
	    problem = user.problems.new(problem_params)
	    
	    if problem.save
	      redirect_to user_path(user)
	    else 
	      render text => "Problem could not be saved"
	    end
	end

	def destroy
		problem = Problem.find_by(id: params[:id])
		problem.destroy
		redirect_to user_path
	end

	def form_decision
		@user = User.find_by(id: session[:user_id])
		@problem = Problem.find_by(id: params[:id])
		@decision = @problem.decisions.all
	end

	def result_decision
		@problem = Problem.find_by(id: params[:id])
		@decision = @problem.decisions.all
	end

	def form_crossover
		@user = User.find_by(id: session[:user_id])
		@problem = Problem.find_by(id: params[:id])
		@crossover = @problem.crossovers.all
	end

	private
	def problem_params #STRONG PARAMETERS: Grabs all the parameters for product that would normally go in the create action and inserts into this method, that simplifies the params code for a product
    	params.require(:problem).permit(:title, :description, :category)
    end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/form_crossover.html.erb
<div class="container">
  <div class="row problem-title">
    <div class="col-sm-12">
      <h2 style='margin: 0 auto; border-radius: 25px; border:2px black solid; font-size:26px; width:fit-content; width:-webkit-fit-content; width:-moz-fit-content; padding: 20px;'>
        <%= @problem.title %></h2>
    </div>
  </div>

  <div class="row add-decision">
    <div class="col-sm-12">
      <center><%= button_to "Add a decision", new_user_problem_crossover_path(@user, @problem), :method => "get", :class => "btn btn-primary btn-lg"%></center>
    </div>
  </div>

  <div class="row info">
    <div class="col-sm-8">
      <ul>
        <% @crossover.each do |crossover| %>
          <div class="options" style='border-radius: 25px; border:2px #5bdb99 solid; background-color: #5bdb99; margin:10px; font-size:15px; width:fit-content; width:-webkit-fit-content; width:-moz-fit-content; padding: 10px; display:inline-block;'>
          <h3><%=crossover.title %></h3>
              <ul>

                <h5>Units to sell:</h5>
                  <li>$<%=crossover.units%></li>
                <h5>Fixed cost:</h5>
                  <li>$<%=crossover.fixed_cost%></li>
                <h5>Variable cost:</h5>
                  <li>$<%=crossover.variable_cost.to_f%></li>
              </ul>       
            
              <%= button_to 'Delete', crossover_path(crossover), method: :delete,
                data: { confirm: 'Are you sure?' } %>
          </div>
        <%end%>
      </ul>
    </div>
    <div class="btn-group col-sm-4">
      <%= button_to "Result", user_problem_crossover_path(@user, @problem, @crossover), :method => "get", :class => "btn btn-default btn-circle btn-lg" %>
    </div>
  </div>
</div>

app/views/problems/form_decision.html.erb
<div class="container">
  <div class="row problem-title">
    <div class="col-sm-12">
      <h2 style='margin: 0 auto; border-radius: 25px; border:2px black solid; font-size:26px; width:fit-content; width:-webkit-fit-content; width:-moz-fit-content; padding: 20px;'><%= @problem.title %></h2>
    </div>
  </div>

  <div class="row add-decision">
    <div class="col-sm-12">
      <center><%= button_to "Add a decision", new_user_problem_decision_path(@user, @problem), :method => "get", :class => "btn btn-primary btn-lg"%></center>
    </div>
  </div>

  <div class="row info">
    <div class="col-sm-8">
      <ul>
        <% @decision.each do |decision| %>
          <div class="options" style='border-radius: 25px; border:2px #5bdb99 solid; background-color: #5bdb99; margin:10px; font-size:15px; width:fit-content; width:-webkit-fit-content; width:-moz-fit-content; padding: 10px; display:inline-block;'>
          <h3><%=decision.title %></h3>
            Associated cost: $<%=decision.associated_cost%>
              <ul>
                <h5>Favorable market:</h5>
                  <li>Probability: <%=decision.favorable_probability %>%</li>
                  <li>Expected financial result: $<%=decision.favorable_result %></li>
              </ul>
              <ul>
                <h5>Unfavorable market:</h5>
                  <li>Probability: <%=decision.unfavorable_probability%>%</li>
                  <li>Expected financial result: $<%=decision.unfavorable_result%></li>
              </ul>          
            
              <%= button_to 'Delete', decision_path(decision), 
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
          </div>
        <%end%>
      </ul>
    </div>
    <div class="btn-group col-sm-4">
      <%= button_to "Result", result_decision_user_problem_path(@user, @problem), :method => "get", :class => "btn btn-default btn-circle btn-lg" %>
    </div>
  </div>
</div>

app/views/problems/index.html.erb
<h1>Problems</h1>
	<% @problems.each do |problem|%>
		<strong><%=	link_to "#{problem.title}", problem_path(problem.id)%></strong><br>
		<%=	problem.title %><br>
<%end%>

app/views/problems/new.html.erb
<div class="container">
	<div class="row new-problem">
		<h2>Enter in the form the problem you need help with:</h2>
			<div class="col-sm-12">
			  <%= form_for @new_problem, url: user_problems_path(@user, @new_problem), html: { method: :post } do |f|%>
			    
			    <div class="form-group">
			      <%= f.label(:title, "Title *", class: "col-sm-4 control-label") %>
			      <div class="col-sm-4" style="margin:2px;">
			        <%= f.text_field :title, placeholder:"Give your problem a title", class: "form-control" %>
			      </div>
			    </div>

			    <div class="form-group">
			      <%= f.label(:description, "Description *", class: "col-sm-4 control-label") %>
			      <div class="col-sm-4" style="margin:2px;">
			        <%= f.text_field :description, placeholder:"Describe your problem a little", class: "form-control" %>
			      </div>
			    </div>

			    <div class="form-group">
			      <%= f.label(:category, "Category *", class: "col-sm-4 control-label") %>
			      <div class="col-sm-4" style="margin:2px;">
			        <%= f.select(:category, ['Decision Tree Tool','Break Even Analysis','Crossover Analysis'])%><br>
			      </div>
			    </div>
				<br>
			    <div class="form-group">
			      <div class="col-sm-4" style="margin:20px;">
			        <%= f.submit "Add Problem", class: "btn btn-primary col-sm-12"%>
			      </div>
			    </div>
			  <% end %>
			</div> 
	</div>
</div>

app/views/problems/result_decision.html.erb
<div class="container">
	
<div class="row result-title">
  <div class="col-sm-12">
  	<h2>The decision you should make is:</h2>
		<% @max = 0 %>
		<% decision_name = "" %>
		<% @decision.each do |decision| %>
			<% fav_prob = ((decision.favorable_probability.to_f)/100) %>
			<% unfav_prob = ((decision.unfavorable_probability.to_f)/100) %>
			<% favorable = (fav_prob)*(decision.favorable_result.to_f) %>
			<% unfavorable = (unfav_prob)*(decision.unfavorable_result.to_f) %>
			<% totalEV = favorable + unfavorable %>
			<% net_gain = totalEV - decision.associated_cost.to_f %><br>

			<% if @max < net_gain %>
				<% @max = net_gain%>
				<% @decision_name = decision.title %>
			<% end %>	
		<%end%>
    <h2 style='border-radius: 25px; border:2px black solid; font-size:26px; width:fit-content; width:-webkit-fit-content; width:-moz-fit-content; padding: 10px;'><%= @decision_name %></h2>
  </div>
</div>

<div class="row result-info">
	<div class="col-sm-8">
		<h4>Why, you may ask?</h4>
		<p>Because the decision to * <strong><%= @decision_name %></strong> * will result in the highest possible net gain. Your net gain will be an average of $<%= @max %>. Despite how high the initial costs, by analyzing the expected value along with those costs, this would be the most efficient option.</p>
	</div>
</div>

</div>

app/views/problems/show.html.erb
<%= @problem.title %>