config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#home'

  resources :users, only: [:new, :show, :create] do
    resources :problems, only: [:index, :show, :new, :create, :destroy] do 
      member do 
        get :form_decision, :result_decision, :form_crossover
      end
      resources :decisions, only: [:index, :show, :new, :create] 
      resources :break_evens, only: [:index, :new, :show, :create, :destroy]
      resources :crossovers, only: [:index, :new, :show, :create]
    end
  end
  
  resources :decisions, only: [:destroy]
  resources :crossovers, only: [:destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


end

app/models/break_even.rb
class BreakEven < ApplicationRecord
	belongs_to :problem
end

app/controllers/break_evens_controller.rb
class BreakEvensController < ApplicationController
	def index
		@user = User.find_by(id: params[:id])
		@break_even = BreakEven.all
	end

	def new
		@user = User.find_by(id: params[:user_id])
		@problem = Problem.find_by(id: params[:problem_id])
		@new_break_even = BreakEven.new
	end

	def show
		@user = User.find_by(id: params[:user_id])
		@problem = Problem.find_by(id: params[:problem_id])
		@break_even = @problem.break_evens.all
	end

	def create
		@user = User.find_by(id: params[:user_id])
		@problem = @user.problems.find_by(id: params[:problem_id])
		@break_even = @problem.break_evens.new(breakeven_params)
		if @break_even.save
			redirect_to user_problem_break_even_path(@user, @problem, @break_even)
		else
			render text => "Break Even Analysis not saved"
		end
	end

	def form_break_even
		@user = User.find_by(id: session[:user_id])
		@problem = Problem.find_by(id: params[:id])
		@break_even = @problem.break_evens.all
	end

	def destroy
		@user = User.find_by(id: params[:user_id])
		@problem = Problem.find_by(id: params[:problem_id])
		break_even = @problem.break_evens.find_by(id: params[:id])
		break_even.destroy
		redirect_to form_break_even_user_problem_path(@user, @problem)
	end

	private
	def breakeven_params
		params.require(:break_even).permit(:fixed_costs, :selling_price, :variable_cost)
	end

end

app/helpers/break_evens_helper.rb
module BreakEvensHelper
end

app/helpers/breakevens_helper.rb
module BreakevensHelper
end

app/views/break_evens/new.html.erb
<div class="container">
  <div class="row problem-title">
    <div class="col-sm-12">
      <h2 style='margin: 0 auto; border-radius: 25px; border:2px black solid; font-size:26px; width:fit-content; width:-webkit-fit-content; width:-moz-fit-content; padding: 20px;'><%= @problem.title %></h2>
      <h3>Fill out this form to create a decision option</h3><br>
    </div>
  </div>

  <div class="row info">
    <%= form_for @new_break_even, url:user_problem_break_evens_path(@user, @problem, @break_even) do |f|%>
      <div class="col-sm-8"> 
        <div class="form-horizontal">
          <div class="form-group">
            <%= f.label(:fixed_costs, "Fixed costs *", class: "col-sm-2 control-label") %>
            <div class="col-sm-8">
                <%= f.number_field :fixed_costs, placeholder:"What are the fixed costs?", class: "form-control"  %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label(:selling_price, "Selling price *", class: "col-sm-2 control-label") %>
            <div class="col-sm-8">
                <%= f.number_field :selling_price, placeholder:"How much are you selling each item for?", class: "form-control"  %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label(:variable_cost, "Variable Cost *", class: "col-sm-2 control-label") %>
            <div class="col-sm-8">
                <%= f.number_field :variable_cost, placeholder:"How much does it cost to create each individual item?", class: "form-control"  %>
            </div>
          </div>  
        </div>
      </div>

      <div class="col-sm-4">
        <%= f.submit "Result", :class => "btn btn-success btn-circle btn-lg" %>
      </div>
      
    <%end%>
  </div>


</div>

app/views/break_evens/show.html.erb
<div class="container">
	<div class="row result-title">
	  <div class="col-sm-12">
	  	<h2>You will start to make a profit when you sell:</h2>
			<% @break_even.each do |breakeven| %>
				<% @units_sold = (breakeven.fixed_costs) / ((breakeven.selling_price)-(breakeven.variable_cost)) %>
			<%end%>
	    <h2 style='border-radius: 25px; border:2px black solid; font-size:26px; width:fit-content; width:-webkit-fit-content; width:-moz-fit-content; padding: 10px;'><%= @units_sold %> units</h2>
	  </div>
	</div>

	<div class="row result-info">
		<div class="col-sm-8">
			<h4>What's happening here?</h4>
			<p></p>
			<%= button_to "Back to form", new_user_problem_break_even_path(@user, @problem, @breakeven), :method => "get", :class => "btn btn-primary" %>
		</div>
	</div>
</div>