config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#home'

  resources :users, only: [:new, :show, :create] do
    resources :problems, only: [:index, :show, :new, :create, :destroy] do 
      member do 
        get :form_decision, :result_decision, :form_crossover
      end
      resources :decisions, only: [:index, :show, :new, :create] 
      resources :break_evens, only: [:index, :new, :show, :create, :destroy]
      resources :crossovers, only: [:index, :new, :show, :create]
    end
  end
  
  resources :decisions, only: [:destroy]
  resources :crossovers, only: [:destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


end

app/models/user.rb
class User < ApplicationRecord	
	validates :username, presence: true
	validates :email, presence: true, uniqueness: true

	has_many :problems

	has_secure_password


	#calls set_default_role after object is created in memory
	#only if the object user does not exist in the database

	after_initialize :set_default_role, :if => :new_record?
	def set_default_role
		unless self.role
			self.role = :user
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
		# before_action :authorize_user, only: [:show]
	before_action :admin_only, only: [:index]

	def home
		@name = current_user ? @current_user.username : "User"
	end

	def index
		@users = User.all
	end

	def new
	end

	def show
		@name = current_user ? current_user.name : "User"
		@users = current_user
		@user = User.find_by(id: params[:id])
		@problems = Problem.all
	end

	#receives form and creates a user from that data
	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to user_path(@user)
		else
			redirect_to '/'
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/home.html.erb
<div class="container">
	<div class="row">
		<img class="img-responsive center-block" src="http://fullhdpictures.com/wp-content/uploads/2016/04/Business-HD-Wallpapers.jpg" alt="business-man-making-decision">
	</div>	
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<ul>
	<%= @users.each do |user| %>
	<li>Username: <%=user.username %> | Email: <%=user.email%></li>
	<%end%>
</ul>

<%= link_to "Home", root_path %>

app/views/users/show.html.erb
<div class="container">
	<div class="row profile-title">
		<div class="col-sm-12">
			<h1><%= @name %>'s Profile</h1>
		</div>

		<div class="col-sm-6">
			<h4 style="display: inline-block; float: left;">
				With what business problem may we assist you with?
				<%= button_to "+", new_user_problem_path(@users), :method => "get" %>
			</h4>
		</div>
	</div>
	<hr>

	<div class="row category-list">
		<div class="col-sm-6">
			<h4>Tool Categories:</h4>

			<nav>
	              <p role="presentation" class="tool-item"><button class="btn btn-primary decision-tree-btn" style="margin:10px;">Decision Tree Tool</button></p>
	              <p role="presentation" class="tool-item"><button class="btn btn-primary break-even-btn" style="margin:10px;">Break Even Analysis</button></p>
	              <p role="presentation" class="tool-item"><button class="btn btn-primary crossover-btn" style="margin:10px;">Crossover Analysis</button></p>
	        </nav>
		</div>

		<div id="problems" class="col-sm-6" style='border-radius: 25px; border:2px #5bdb99 solid; background-color: #5bdb99; margin:10px; width:fit-content; width:-webkit-fit-content; width:-moz-fit-content; padding: 10px; display:inline-block;'>
		</div>
	</div>
</div>